baseURL: 'https://slashtechno.com/'
languageCode: en-us
title: slashtechno
description: "Hi! I'm a student and an aspiring software developer."
theme: "lynx"

params:
  CanonicalLinkText: "Also published at"
  author:
    name: slashtechno
    headline: Hi! I'm a student and an aspiring software developer.
    links:
      - globe: 
          href: "https://angad.me"
          text: "My website/portfolio/blog"
          icon: "globe"
      # - link: 
      #     href: "styles/"
      #     text: "All the link styles"
      #     target: "_self"
      - github: "https://github.com/slashtechno"
      - Mastodon: 
          href: "https://fosstodon.org/@slashtechno"
          text: "Mastodon"  
# theme: PaperMod
# params:
#   title: slashtechno
#   description: "This is my website."
#   env: production # Enables enhanced SEO
#   images: [logo.png]
#   profileMode:
#     enabled: true
#     title: "I am slashtechno."
#     subtitle: "This is my website."
#     buttons:
#       - name: Blog Posts
#         url: "/blog/"
#       - name: Who am I?
#         url: "/about/"
#   socialIcons: # Show the respective social icon linked to the corresponding URL
#     - name: github
#       url: "https://github.com/slashtechno"
#     - name: mastodon 
#       url: "https://fosstodon.org/@slashtechno"
#   cover:
#     linkFullImages: true # Clicking a post's cover image opens the image in a new tab
#   # Other settings
#   ShowBreadcrumbs: true # Show the path to a page'
#   ShowReadingTime: true # Show the page's reading time
#   # ShowShareButtons: true # Show the share buttons
#   # ShowPostNavLinks: true # Show navigation links under a post
# outputs:
#     home:
#         - HTML
#         - JSON
# menu:
#   main:
#     - indentifier: github
#       name: Github
#       url: https://github.com/slashtechno
#       weight: 2
#     - indentifier: search
#       name: Search
#       url: search/
#       weight: 1
